# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libfftw3-dev
    - libgsl0-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - devscripts
    - libomp-dev
    - libcgal-dev

env:
  global:
    - RGL_USE_NULL=TRUE
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

notifications:   
  email:   
    on_success: change   
    on_failure: change
